"""
Utilities for generating dbt models and schema files from database metadata.
"""

import os

import psycopg2
import psycopg2.extras
import yaml


def list_tables_with_columns(conn, schema: str = "public") -> list[dict]:
    """Return table metadata from PostgreSQL in the same shape used by the notebook."""
    tables: dict[str, dict] = {}

    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(
            """
            SELECT table_name, column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema = %s
            ORDER BY table_name, ordinal_position
            """,
            (schema,),
        )
        for row in cur.fetchall():
            table_name = row["table_name"]
            table_entry = tables.setdefault(
                table_name,
                {
                    "name": table_name,
                    "fqn": f"{schema}.{table_name}",
                    "columns": [],
                },
            )
            table_entry["columns"].append(
                {
                    "name": row["column_name"],
                    "dataType": row["data_type"].upper(),
                    "nullable": row["is_nullable"] == "YES",
                }
            )

    return list(tables.values())


def get_sample_rows(conn, table_name: str, limit: int = 10) -> list[dict]:
    """Fetch sample rows from a table."""
    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(f'SELECT * FROM "{table_name}" LIMIT {limit}')
            return [dict(row) for row in cur.fetchall()]
    except Exception as e:
        print(f"  Warning: sample rows failed for {table_name}: {e}")
        return []


def generate_sources_yml(
    tables: list[str],
    source_name: str = "retail",
    schema: str = "public",
    database: str = "retail",
) -> str:
    """Generate dbt sources.yml content."""
    sources_dict = {
        "version": 2,
        "sources": [
            {
                "name": source_name,
                "description": "Raw retail data from PostgreSQL",
                "database": database,
                "schema": schema,
                "tables": [
                    {"name": t, "description": f"Raw {t} table"} for t in tables
                ],
            }
        ],
    }
    return yaml.dump(
        sources_dict, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


def generate_staging_model(table_name: str, source_name: str = "retail") -> str:
    """Generate a simple staging SQL model."""
    return f"""-- Staging model for {table_name}
-- Auto-generated by retail-dbt-poc pipeline
{{{{ config(materialized='view') }}}}

select *
from {{{{ source('{source_name}', '{table_name}') }}}}
"""


def merge_schema_ymls(per_table_schemas: list[dict]) -> str:
    """
    Merge multiple per-table schema dicts into one schema.yml.
    Each dict should have structure: {models: [{name: ..., columns: [...]}]}
    """
    all_models = []
    for schema_dict in per_table_schemas:
        if schema_dict and "models" in schema_dict:
            all_models.extend(schema_dict["models"])

    combined = {"version": 2, "models": all_models}
    return yaml.dump(
        combined, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


def write_staging_models(
    dbt_project_dir: str,
    tables: list[str],
    source_name: str = "retail",
):
    """
    Write staging SQL models and sources.yml — NO schema.yml.
    Run this BEFORE dbt_profiler so staging views exist when profiling runs.
    schema.yml (LLM-generated tests) is written separately by write_schema_yml()
    after profiler stats are available.
    """
    staging_dir = os.path.join(dbt_project_dir, "models", "staging")
    os.makedirs(staging_dir, exist_ok=True)

    sources_path = os.path.join(staging_dir, "sources.yml")
    with open(sources_path, "w") as f:
        f.write(generate_sources_yml(tables, source_name))
    print(f"  Written: {sources_path}")

    for table in tables:
        model_path = os.path.join(staging_dir, f"stg_{table}.sql")
        with open(model_path, "w") as f:
            f.write(generate_staging_model(table, source_name))
        print(f"  Written: {model_path}")


def write_profiling_models(
    dbt_project_dir: str,
    tables: list[str],
) -> list[dict]:
    """
    Write models/profiling/profile_stg_{table}.sql and schema.yml.
    Each model calls dbt_profiler.get_profile() — dbt_profiler v1.0.0+ API.
    Returns list of {name, description} entries for the caller if needed.
    """
    profiling_dir = os.path.join(dbt_project_dir, "models", "profiling")
    os.makedirs(profiling_dir, exist_ok=True)

    entries = []
    for table in tables:
        model_name = f"stg_{table}"
        profile_model_name = f"profile_{model_name}"
        # {{ and }} in Python strings produce literal { and } — required to emit
        # Jinja expression syntax {{ ... }} that dbt expects.
        sql_content = (
            "{{{{ config(materialized='table', schema='profiling') }}}}\n\n"
            "{{{{ dbt_profiler.get_profile(relation=ref('{}')) }}}}\n"
        ).format(model_name)
        sql_path = os.path.join(profiling_dir, f"{profile_model_name}.sql")
        with open(sql_path, "w") as f:
            f.write(sql_content)
        print(f"  Written: {sql_path}")
        entries.append(
            {
                "name": profile_model_name,
                "description": f"dbt_profiler column-level profile for {model_name}",
            }
        )

    schema_doc = {"version": 2, "models": entries}
    schema_path = os.path.join(profiling_dir, "schema.yml")
    with open(schema_path, "w") as f:
        yaml.dump(schema_doc, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    print(f"  Written: {schema_path}")
    return entries


def write_schema_yml(dbt_project_dir: str, merged_schema_yml: str):
    """Write models/staging/schema.yml (LLM-generated tests). Call after LLM step."""
    staging_dir = os.path.join(dbt_project_dir, "models", "staging")
    os.makedirs(staging_dir, exist_ok=True)
    schema_path = os.path.join(staging_dir, "schema.yml")
    with open(schema_path, "w") as f:
        f.write(merged_schema_yml)
    print(f"  Written: {schema_path}")


def load_profiler_stats(
    conn,
    tables: list[str],
    profiling_schema: str = "profiling",
) -> dict:
    """
    Query dbt_profiler output tables and return stats in the same shape as
    compute_column_stats() — {table: {col: {metric: value}}}.

    dbt_profiler profile table columns:
      column_name, data_type, row_count, not_null_proportion, distinct_proportion,
      is_unique, min, max, avg, std_deviation, median, profiled_at

    Falls back to empty dict per table if the profiler table doesn't exist yet.
    """
    all_stats = {}
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        for table in tables:
            profile_table = f'profile_stg_{table}'
            try:
                cur.execute(
                    f'SELECT * FROM "{profiling_schema}"."{profile_table}"'
                )
                rows = cur.fetchall()
            except Exception:
                conn.rollback()
                all_stats[table] = {}
                continue

            table_stats = {}
            for row in rows:
                col = row["column_name"]
                not_null_prop = float(row.get("not_null_proportion") or 0)
                total = int(row.get("row_count") or 0)
                distinct_prop = float(row.get("distinct_proportion") or 0)
                table_stats[col] = {
                    "total_count":      total,
                    "null_count":       round((1 - not_null_prop) * total),
                    "null_rate":        round(1 - not_null_prop, 6),
                    "not_null_proportion": not_null_prop,
                    "distinct_count":   round(distinct_prop * total),
                    "distinct_proportion": distinct_prop,
                    "uniqueness_score": float(row.get("distinct_proportion") or 0),
                    "is_unique":        bool(row.get("is_unique")),
                    "min_val":          row.get("min"),
                    "max_val":          row.get("max"),
                    "mean":             row.get("avg"),
                    "std_deviation":    row.get("std_deviation"),
                    "median":           row.get("median"),
                    "zero_count":       None,
                }
            all_stats[table] = table_stats
    return all_stats


def write_dbt_files(
    dbt_project_dir: str,
    tables: list[str],
    merged_schema_yml: str,
    source_name: str = "retail",
):
    """
    Write all generated dbt files to the project directory:
    - models/staging/sources.yml
    - models/staging/schema.yml (LLM-generated tests)
    - models/staging/stg_{table}.sql for each table
    """
    staging_dir = os.path.join(dbt_project_dir, "models", "staging")
    os.makedirs(staging_dir, exist_ok=True)

    # sources.yml
    sources_path = os.path.join(staging_dir, "sources.yml")
    with open(sources_path, "w") as f:
        f.write(generate_sources_yml(tables, source_name))
    print(f"  Written: {sources_path}")

    # schema.yml (LLM-generated)
    schema_path = os.path.join(staging_dir, "schema.yml")
    with open(schema_path, "w") as f:
        f.write(merged_schema_yml)
    print(f"  Written: {schema_path}")

    # stg_*.sql models
    for table in tables:
        model_path = os.path.join(staging_dir, f"stg_{table}.sql")
        with open(model_path, "w") as f:
            f.write(generate_staging_model(table, source_name))
        print(f"  Written: {model_path}")
