"""
Utilities for generating dbt models and schema files from database metadata.
"""

import os
import yaml
import psycopg2
import psycopg2.extras
from typing import Any


def compute_column_stats(conn, table_name: str, columns: list[dict]) -> dict:
    """
    Compute per-column statistics: null_count, distinct_count, zero_count, min/max.
    Returns dict: col_name -> stats_dict
    """
    stats = {}
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        # Get total count once
        cur.execute(f'SELECT COUNT(*) as total FROM "{table_name}"')
        total = cur.fetchone()["total"]

        for col in columns:
            col_name = col["name"]
            col_type = col.get("dataType", "VARCHAR").upper()

            col_stats = {"total_count": total, "null_count": 0, "null_rate": 0.0,
                         "distinct_count": 0, "uniqueness_score": 0.0,
                         "zero_count": None, "min_val": None, "max_val": None}

            try:
                # Null count
                cur.execute(f'SELECT COUNT(*) as cnt FROM "{table_name}" WHERE "{col_name}" IS NULL')
                null_count = cur.fetchone()["cnt"]
                col_stats["null_count"] = null_count
                col_stats["null_rate"] = null_count / total if total > 0 else 0.0

                # Distinct count
                cur.execute(f'SELECT COUNT(DISTINCT "{col_name}") as cnt FROM "{table_name}"')
                distinct_count = cur.fetchone()["cnt"]
                col_stats["distinct_count"] = distinct_count
                non_null_count = total - null_count
                col_stats["uniqueness_score"] = distinct_count / non_null_count if non_null_count > 0 else 0.0

                # Numeric stats
                numeric_types = {"INT", "INTEGER", "BIGINT", "SMALLINT", "NUMERIC", "DECIMAL",
                                 "FLOAT", "REAL", "DOUBLE", "NUMBER", "INT4", "INT8", "FLOAT4", "FLOAT8"}
                is_numeric = any(t in col_type for t in numeric_types)

                if is_numeric:
                    cur.execute(f'SELECT MIN("{col_name}") as mn, MAX("{col_name}") as mx, '
                                f'COUNT(*) FILTER (WHERE "{col_name}" = 0) as zeros '
                                f'FROM "{table_name}"')
                    row = cur.fetchone()
                    col_stats["min_val"] = row["mn"]
                    col_stats["max_val"] = row["mx"]
                    col_stats["zero_count"] = row["zeros"]

            except Exception as e:
                print(f"  Warning: stats failed for {table_name}.{col_name}: {e}")
                conn.rollback()

            stats[col_name] = col_stats

    return stats


def get_sample_rows(conn, table_name: str, limit: int = 10) -> list[dict]:
    """Fetch sample rows from a table."""
    try:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(f'SELECT * FROM "{table_name}" LIMIT {limit}')
            return [dict(row) for row in cur.fetchall()]
    except Exception as e:
        print(f"  Warning: sample rows failed for {table_name}: {e}")
        return []


def generate_sources_yml(tables: list[str], source_name: str = "retail",
                          schema: str = "public", database: str = "retail") -> str:
    """Generate dbt sources.yml content."""
    sources_dict = {
        "version": 2,
        "sources": [
            {
                "name": source_name,
                "description": "Raw retail data from PostgreSQL",
                "database": database,
                "schema": schema,
                "tables": [{"name": t, "description": f"Raw {t} table"} for t in tables],
            }
        ]
    }
    return yaml.dump(sources_dict, default_flow_style=False, sort_keys=False, allow_unicode=True)


def generate_staging_model(table_name: str, source_name: str = "retail") -> str:
    """Generate a simple staging SQL model."""
    return f"""-- Staging model for {table_name}
-- Auto-generated by retail-dbt-poc pipeline
{{{{ config(materialized='view') }}}}

select *
from {{{{ source('{source_name}', '{table_name}') }}}}
"""


def merge_schema_ymls(per_table_schemas: list[dict]) -> str:
    """
    Merge multiple per-table schema dicts into one schema.yml.
    Each dict should have structure: {models: [{name: ..., columns: [...]}]}
    """
    all_models = []
    for schema_dict in per_table_schemas:
        if schema_dict and "models" in schema_dict:
            all_models.extend(schema_dict["models"])

    combined = {"version": 2, "models": all_models}
    return yaml.dump(combined, default_flow_style=False, sort_keys=False, allow_unicode=True)


def write_dbt_files(dbt_project_dir: str, tables: list[str],
                    merged_schema_yml: str, source_name: str = "retail"):
    """
    Write all generated dbt files to the project directory:
    - models/staging/sources.yml
    - models/staging/schema.yml (LLM-generated tests)
    - models/staging/stg_{table}.sql for each table
    """
    staging_dir = os.path.join(dbt_project_dir, "models", "staging")
    os.makedirs(staging_dir, exist_ok=True)

    # sources.yml
    sources_path = os.path.join(staging_dir, "sources.yml")
    with open(sources_path, "w") as f:
        f.write(generate_sources_yml(tables, source_name))
    print(f"  Written: {sources_path}")

    # schema.yml (LLM-generated)
    schema_path = os.path.join(staging_dir, "schema.yml")
    with open(schema_path, "w") as f:
        f.write(merged_schema_yml)
    print(f"  Written: {schema_path}")

    # stg_*.sql models
    for table in tables:
        model_path = os.path.join(staging_dir, f"stg_{table}.sql")
        with open(model_path, "w") as f:
            f.write(generate_staging_model(table, source_name))
        print(f"  Written: {model_path}")
