datalens_trino:
  target: prod
  outputs:
    prod:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'localhost') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: admin
      database: postgres
      schema: cdm
      http_scheme: http
      session_properties:
        query_max_run_time: 5d
    dev:
      type: trino
      method: none
      host: "{{ env_var('TRINO_HOST', 'localhost') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: admin
      database: postgres
      schema: cdm
      http_scheme: http
      session_properties:
        query_max_run_time: 5d
